# name: qlearning
channels:
   - conda-forge
   - pytorch
dependencies:
   - python=3.7
   - swig
   - torch::pytorch #=1.2.0
   - torch::torchvision #=0.4.0
   - torch::cudatoolkit #=10.0
   - matplotlib #=3.0.2
   - scipy #=1.1.0
   - pip #=20.0.2
   - pip:
      - gym==0.14.0
      - box2d-py==2.3.8
      - atari-py==0.2.6 
      - rope
      - jedi
      - ipykernel
      - pylint
      - opencv-contrib-python
      - tqdm
      - imageio
      - numpy

